/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uis_monitor_Rtsplayer */

#ifndef _Included_com_uis_monitor_Rtsplayer
#define _Included_com_uis_monitor_Rtsplayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uis_monitor_Rtsplayer
 * Method:    CreateRec
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_uis_monitor_Rtsplayer_CreateRec
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint);

/*
 * Class:     uis_monitor_Rtsplayer
 * Method:    StartRec
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_uis_monitor_Rtsplayer_StartRec
  (JNIEnv *, jobject, jint);

/*
 * Class:     uis_monitor_Rtsplayer
 * Method:    StopRec
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_uis_monitor_Rtsplayer_StopRec
  (JNIEnv *, jobject, jint);

/*
 * Class:     uis_monitor_Rtsplayer
 * Method:    DestroyRec
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_uis_monitor_Rtsplayer_DestroyRec
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
