/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_streamplayer_Rtsplayer */

#ifndef _Included_my_streamplayer_Rtsplayer
#define _Included_my_streamplayer_Rtsplayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_streamplayer_Rtsplayer
 * Method:    native_gl_resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_my_streamplayer_Rtsplayer_native_1gl_1resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     my_streamplayer_Rtsplayer
 * Method:    native_gl_render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_my_streamplayer_Rtsplayer_native_1gl_1render
  (JNIEnv *, jclass);

/*
 * Class:     my_streamplayer_Rtsplayer
 * Method:    CreateRec
 * Signature: (Landroid/graphics/Bitmap;Ljava/lang/String;Ljava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_my_streamplayer_Rtsplayer_CreateRec
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint);

/*
 * Class:     my_streamplayer_Rtsplayer
 * Method:    StartRec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_my_streamplayer_Rtsplayer_StartRec
  (JNIEnv *, jobject, jint);

/*
 * Class:     my_streamplayer_Rtsplayer
 * Method:    StopRec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_my_streamplayer_Rtsplayer_StopRec
  (JNIEnv *, jobject, jint);

/*
 * Class:     my_streamplayer_Rtsplayer
 * Method:    DestroyRec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_my_streamplayer_Rtsplayer_DestroyRec
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
