/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_streamplayer_Rtsplayer */

#ifndef _Included_my_streamplayer_Rtsplayer
#define _Included_my_streamplayer_Rtsplayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_streamplayer_Rtsplayer
 * Method:    CreateRec
 * Signature: ([B[BIIII)V
 */
JNIEXPORT void JNICALL Java_my_streamplayer_Rtsplayer_CreateRec
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     my_streamplayer_Rtsplayer
 * Method:    StartRec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_my_streamplayer_Rtsplayer_StartRec
  (JNIEnv *, jobject, jint);

/*
 * Class:     my_streamplayer_Rtsplayer
 * Method:    StopRec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_my_streamplayer_Rtsplayer_StopRec
  (JNIEnv *, jobject, jint);

/*
 * Class:     my_streamplayer_Rtsplayer
 * Method:    DestroyRec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_my_streamplayer_Rtsplayer_DestroyRec
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
